name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'


      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './publish' 
          
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ThomasWoodcockApi
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: './myapp'
