name: Deploy

on:
  push:
    branches: [ master ]

env:
  PROJECT_PATH: 'src/ThomasWoodcock.Service/ThomasWoodcock.Service.csproj'
  PUBLISH_PATH: './publish'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Replace Tokens
        run: |
          find . -type f -name 'appsettings*.json' -exec sed -i ''s/#{DatabaseConnection}#/${{ secrets.DATABASECONNECTION }}/g'' {} \;
          find . -type f -name 'appsettings*.json' -exec sed -i ''s/#{DatabaseName}#/${{ secrets.DATABASENAME }}/g'' {} \;

      - name: Build and Publish
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          dotnet build ${{ env.PROJECT_PATH }} --configuration Release
          dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_PATH }} 
          
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ThomasWoodcockApi
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: ${{ env.PUBLISH_PATH }}
